### ISSUE TITLE
Location of xpath post button

### ISSUE THREAD

**Issue by agung2001** [lalongooo/selenium-fb-group-poster#1]
I've got this error from fbposter.py, i think the facebook has change the post button script
Traceback (most recent call last):
  File "fbposter.py", line 81, in <module>
    main()
  File "fbposter.py", line 74, in main
    button = buttons[0]
IndexError: list index out of range

**Comment by iamyorchdev** [comment]
Fixed in the latest commit e0245a5198f5e1c83f3390449c50789ad0782f8d
