### ISSUE TITLE
NameError: global name 'button' is not defined

### ISSUE THREAD

**Issue by davidkimberley** [lalongooo/selenium-fb-group-poster#2]
corrected now

**Comment by iamyorchdev** [comment]
@davidkimberley how did you fix it?

**Comment by davidkimberley** [comment]
@lalongooo  I made the browser size go to full screen. Basically the post button needs to be visible on the page in order for the post to be made. I had one of my accounts roadblocked because I was doing something in other windows while running the script, some posts got on but fb eventually picked it up. For perfect runs its better to keep the mechanized browser as the active browser.

**Comment by iamyorchdev** [comment]
Yes,that's the way the script works. Just asked in case you found another workaround.

I will close this issue.
